import type { CalculatorMeta, Category, CategoryMeta } from "@/types/calculator";

export const CATEGORIES: CategoryMeta[] = [
  {
    id: "finance",
    name: "Finance",
    shortDesc: "SIP, EMI, taxes, investments",
    icon: "TrendingUp",
    color: "finance",
  },
  {
    id: "finance-india",
    name: "Finance (India)",
    shortDesc: "NSC, PPF, SSY, regime, tax slabs",
    icon: "Landmark",
    color: "finance",
  },
  {
    id: "math",
    name: "Math",
    shortDesc: "Algebra, statistics, geometry",
    icon: "Sigma",
    color: "math",
  },
  {
    id: "geometry",
    name: "Geometry",
    shortDesc: "Areas, volumes, triangles, solids",
    icon: "Triangle",
    color: "primary",
  },
  {
    id: "health",
    name: "Health & Fitness",
    shortDesc: "BMI, BMR, calories, hydration",
    icon: "HeartPulse",
    color: "health",
  },
  {
    id: "converter",
    name: "Converters",
    shortDesc: "Units, currency, sizing",
    icon: "ArrowLeftRight",
    color: "converter",
  },
  {
    id: "datetime",
    name: "Date & Time",
    shortDesc: "Age, duration, time zones",
    icon: "Calendar",
    color: "datetime",
  },
  {
    id: "crypto",
    name: "Crypto & Stock",
    shortDesc: "Crypto PnL, staking, stocks",
    icon: "Coins",
    color: "crypto",
  },
  {
    id: "construction",
    name: "Construction & DIY",
    shortDesc: "Concrete, paint, lumber, tiles",
    icon: "Hammer",
    color: "accent",
  },
  {
    id: "automotive",
    name: "Automotive",
    shortDesc: "Fuel, mileage, horsepower",
    icon: "Car",
    color: "secondary",
  },
  {
    id: "physics",
    name: "Physics",
    shortDesc: "Force, energy, motion, Ohm",
    icon: "Atom",
    color: "datetime",
  },
  {
    id: "chemistry",
    name: "Chemistry",
    shortDesc: "Molarity, pH, ideal gas",
    icon: "FlaskRound",
    color: "health",
  },
  {
    id: "electrical",
    name: "Electrical",
    shortDesc: "Resistors, voltage drop, LED",
    icon: "Zap",
    color: "accent",
  },
  {
    id: "cooking",
    name: "Cooking & Food",
    shortDesc: "Recipe scale, oven, macros",
    icon: "ChefHat",
    color: "error",
  },
  {
    id: "lifestyle",
    name: "Everyday & Lifestyle",
    shortDesc: "GPA, tip, age, zodiac, carbon",
    icon: "Sparkles",
    color: "secondary",
  },
  {
    id: "developer",
    name: "Developer / Tools",
    shortDesc: "Subnet, base64, hash, color",
    icon: "Terminal",
    color: "text",
  },
  {
    id: "weather",
    name: "Weather",
    shortDesc: "Wind chill, heat index, UV",
    icon: "Cloud",
    color: "datetime",
  },
  {
    id: "sports",
    name: "Sports",
    shortDesc: "Cricket RR, golf, fantasy",
    icon: "Trophy",
    color: "success",
  },
];

const C = (
  id: string,
  name: string,
  shortDesc: string,
  category: Category,
  icon: string,
  extra: Partial<CalculatorMeta> = {},
): CalculatorMeta => ({
  id,
  name,
  shortDesc,
  category,
  icon,
  ...extra,
});

export const CALCULATORS: CalculatorMeta[] = [
  // ── Finance (24 existing + 44 new = 68) ────────────────────────────────
  C("sip", "SIP Calculator", "Monthly mutual-fund SIP returns", "finance", "TrendingUp", {
    hasChart: true,
    has3DView: true,
  }),
  C("lumpsum", "Lumpsum Calculator", "One-time investment growth", "finance", "Wallet", {
    hasChart: true,
    has3DView: true,
  }),
  C("emi", "EMI Calculator", "Monthly loan installment", "finance", "CreditCard", {
    hasChart: true,
    has3DView: true,
  }),
  C("simple-interest", "Simple Interest", "Flat interest calculation", "finance", "Banknote", {
    hasChart: true,
  }),
  C("compound-interest", "Compound Interest", "Power of compounding", "finance", "Layers", {
    hasChart: true,
    has3DView: true,
  }),
  C("fd-rd", "FD / RD Calculator", "Fixed & recurring deposits", "finance", "Lock", {
    hasChart: true,
  }),
  C("ppf", "PPF Calculator", "Public provident fund", "finance", "ShieldCheck", { hasChart: true }),
  C(
    "currency-converter",
    "Currency Converter",
    "FX between major currencies",
    "finance",
    "ArrowLeftRight",
  ),
  C("gst", "GST Calculator", "Inclusive / exclusive GST", "finance", "Receipt"),
  C("profit-loss", "Profit & Loss", "Trading & business margins", "finance", "BarChart3", {
    hasChart: true,
  }),
  C("discount", "Discount Calculator", "Sale-price savings", "finance", "Tag"),
  C("salary", "Salary Calculator", "CTC to in-hand", "finance", "Briefcase", { hasChart: true }),
  C("income-tax", "Income Tax", "Old vs new tax regime", "finance", "FileText", { hasChart: true }),
  C("mortgage", "Mortgage", "Home loan EMI & total interest", "finance", "Home", {
    hasChart: true,
    has3DView: true,
  }),
  C("retirement", "Retirement Planner", "Corpus you need", "finance", "Sun", {
    hasChart: true,
    has3DView: true,
  }),
  C("roi", "ROI Calculator", "Return on investment", "finance", "Activity"),
  C("nps", "NPS Calculator", "National pension scheme", "finance", "Umbrella", { hasChart: true }),
  C("cagr", "CAGR Calculator", "Compound annual growth rate", "finance", "LineChart"),
  C("hra", "HRA Calculator", "House rent allowance exemption", "finance", "Building"),
  C("gratuity", "Gratuity", "End-of-service gratuity", "finance", "Gift"),
  C("epf", "EPF Calculator", "Employee provident fund", "finance", "Users", { hasChart: true }),
  C("home-loan-vs-rent", "Home Loan vs Rent", "Buy vs rent comparison", "finance", "GitCompare", {
    hasChart: true,
    has3DView: true,
  }),
  C("net-worth", "Net Worth", "Assets minus liabilities", "finance", "PieChart", {
    hasChart: true,
    has3DView: true,
  }),
  C("break-even", "Break-Even", "Break-even point", "finance", "Flag", { hasChart: true }),
  C(
    "amortization",
    "Amortization Schedule",
    "Month-by-month loan breakup",
    "finance",
    "TableProperties",
  ),
  C("mortgage-payoff", "Mortgage Payoff", "Extra-payment savings", "finance", "Flame"),
  C("refinance", "Refinance Calculator", "Break-even on refinance", "finance", "Repeat"),
  C("house-affordability", "House Affordability", "Max loan + max price", "finance", "Home"),
  C("rent-affordability", "Rent Affordability", "Max rent by income", "finance", "Building"),
  C("down-payment", "Down Payment", "Down + LTV", "finance", "Banknote"),
  C("rent-vs-buy", "Rent vs Buy (NPV)", "Long-horizon NPV comparison", "finance", "GitCompare"),
  C("apr", "APR (with fees)", "True APR including upfront fees", "finance", "Percent"),
  C("auto-loan", "Auto Loan", "Car EMI", "finance", "Car"),
  C("auto-lease", "Auto Lease", "Lease monthly payment", "finance", "Key"),
  C(
    "credit-card-payoff",
    "Credit Card Payoff",
    "Months to clear + interest",
    "finance",
    "CreditCard",
  ),
  C(
    "credit-card-min",
    "Credit Card Min Payment",
    "Min-payment trap simulator",
    "finance",
    "AlertTriangle",
  ),
  C("debt-snowball", "Debt Snowball", "Pay-off speed", "finance", "ListOrdered"),
  C("debt-consolidation", "Debt Consolidation", "Saving by consolidating", "finance", "Combine"),
  C("dti", "DTI Ratio", "Debt-to-income with verdict", "finance", "Scale"),
  C("student-loan", "Student Loan", "Education EMI", "finance", "GraduationCap"),
  C("college-cost", "College Cost", "Future cost inflated", "finance", "School"),
  C("payback-period", "Payback Period", "Years to recover investment", "finance", "Timer"),
  C("npv", "NPV", "Net present value", "finance", "Sigma"),
  C("irr", "IRR", "Internal rate of return", "finance", "TrendingUp"),
  C("present-value", "Present Value", "PV of future amount", "finance", "ArrowDown"),
  C("future-value", "Future Value", "FV of present amount", "finance", "ArrowUp"),
  C("annuity-fv", "Annuity FV", "Future value of periodic payments", "finance", "Repeat"),
  C("annuity-payout", "Annuity Payout", "Monthly payout from corpus", "finance", "Banknote"),
  C("bond", "Bond Pricing", "Bond price from coupon + YTM", "finance", "Receipt"),
  C(
    "mutual-fund-returns",
    "Mutual Fund Returns",
    "Absolute + CAGR from NAVs",
    "finance",
    "TrendingUp",
  ),
  C("inflation", "Inflation Calculator", "Future cost / real value", "finance", "Flame"),
  C("sales-tax", "Sales Tax", "Tax + total", "finance", "Receipt"),
  C("vat", "VAT Calculator", "Inclusive/exclusive VAT", "finance", "Receipt"),
  C("tip", "Tip Calculator", "Tip + per person", "finance", "HandCoins"),
  C("commission", "Commission", "Sales commission", "finance", "HandCoins"),
  C("margin-markup", "Margin / Markup", "Profit, margin %, markup %", "finance", "Percent"),
  C("depreciation", "Depreciation", "SL / DDB / SYD methods", "finance", "TrendingDown"),
  C("budget", "Budget Calculator", "Income/expense → savings rate", "finance", "Wallet"),
  C("pension", "Pension Planner", "Corpus + monthly payout", "finance", "Umbrella"),
  C("social-security", "Old-Age Benefit", "Estimated monthly benefit", "finance", "Shield"),
  C("equipment-lease", "Equipment Lease", "Generic lease payment", "finance", "Wrench"),
  C("business-loan", "Business Loan EMI", "Business loan", "finance", "Building2"),
  C("personal-loan", "Personal Loan EMI", "Unsecured personal loan", "finance", "User"),
  C("bike-loan", "Bike / Boat Loan", "Two-wheeler / boat loan", "finance", "Bike"),
  C("savings-goal", "Savings Goal", "Monthly savings needed", "finance", "Target"),
  C(
    "interest-rate-solver",
    "Interest Rate Solver",
    "Back-solve rate from EMI",
    "finance",
    "Calculator",
  ),
  C("tenure-solver", "Tenure Solver", "Back-solve tenure", "finance", "Calculator"),

  // ── Finance (India) — 24 new ───────────────────────────────────────────
  C("nsc", "NSC", "National Savings Certificate", "finance-india", "Landmark"),
  C("kvp", "KVP", "Kisan Vikas Patra", "finance-india", "Wheat"),
  C("ssy", "Sukanya Samriddhi", "SSY 21-yr maturity", "finance-india", "Baby"),
  C("apy", "Atal Pension Yojana", "Pension by 60", "finance-india", "Shield"),
  C("scss", "Senior Citizens Saving", "SCSS quarterly payout", "finance-india", "Users"),
  C("pomis", "Post Office MIS", "POMIS monthly payout", "finance-india", "Mail"),
  C("epf-final", "EPF Final Settlement", "EPF at retirement", "finance-india", "Briefcase"),
  C("nps-withdraw", "NPS Withdrawal", "60% lump + 40% annuity", "finance-india", "Umbrella"),
  C("ltcg-equity", "LTCG (Equity)", "Long-term equity gains tax", "finance-india", "BarChart3"),
  C("stcg-equity", "STCG (Equity)", "Short-term equity gains tax", "finance-india", "BarChart2"),
  C("property-gains", "Property Capital Gains", "Indexed LTCG @20%", "finance-india", "Home"),
  C("advance-tax", "Advance Tax", "Quarterly instalments", "finance-india", "Calendar"),
  C("tds", "TDS Calculator", "Tax deducted at source", "finance-india", "Scissors"),
  C("section-80c", "Section 80C", "Tax saver summary", "finance-india", "PiggyBank"),
  C(
    "regime-compare",
    "Old vs New Regime",
    "Side-by-side tax compare",
    "finance-india",
    "GitCompare",
  ),
  C("form-16", "Form 16 In-Hand", "Annual + monthly take-home", "finance-india", "FileText"),
  C("xirr", "XIRR", "Annualized IRR for irregular flows", "finance-india", "TrendingUp"),
  C("swp", "SWP", "Systematic withdrawal lifespan", "finance-india", "ArrowDownToLine"),
  C("stp", "STP", "Systematic transfer plan", "finance-india", "Repeat"),
  C("elss", "ELSS Tax Saver", "ELSS maturity + tax saved", "finance-india", "Sprout"),
  C("step-up-sip", "Step-up SIP", "SIP with annual hike", "finance-india", "TrendingUp"),
  C("sgb", "Sovereign Gold Bond", "SGB maturity + 2.5% interest", "finance-india", "Gem"),
  C("stamp-duty", "Stamp Duty", "Property stamp + registration", "finance-india", "Stamp"),
  C("brokerage", "Brokerage / F&O", "STT + GST + brokerage", "finance-india", "Briefcase"),

  // ── Math (12 existing + 29 new = 41) ───────────────────────────────────
  C("basic", "Basic Calculator", "Everyday arithmetic", "math", "Calculator"),
  C("scientific", "Scientific Calculator", "Trig, log, exp", "math", "FlaskConical"),
  C("percentage", "Percentage", "Percent of, increase, decrease", "math", "Percent"),
  C("fraction", "Fraction Calculator", "Add / multiply fractions", "math", "Divide"),
  C("number-system", "Number System", "Bin / oct / dec / hex", "math", "Code"),
  C("prime-checker", "Prime Checker", "Is N prime? + factors", "math", "Search"),
  C("gcd-lcm", "GCD / LCM", "Greatest common divisor / LCM", "math", "GitMerge"),
  C("statistics", "Statistics", "Mean, median, mode, stddev", "math", "BarChart2", {
    hasChart: true,
  }),
  C("matrix", "Matrix Calculator", "Add / multiply / determinant", "math", "Grid3x3"),
  C("quadratic", "Quadratic Solver", "Roots of ax² + bx + c", "math", "Sigma", {
    hasChart: true,
    has3DView: true,
  }),
  C("logarithm", "Logarithm", "log_b(x) with base picker", "math", "Infinity"),
  C("permutation-combination", "Permutation & Combination", "nPr and nCr", "math", "Shuffle"),
  C("standard-deviation", "Standard Deviation", "σ, variance, mean", "math", "BarChart2"),
  C("variance", "Variance", "σ² of a list", "math", "Sigma"),
  C("mean-median-mode", "Mean / Median / Mode", "All four basics", "math", "BarChart"),
  C("z-score", "Z-Score", "Standardized value", "math", "TrendingUp"),
  C("confidence-interval", "Confidence Interval", "CI for a mean", "math", "BarChart"),
  C("sample-size", "Sample Size", "Survey n calculation", "math", "Users"),
  C("probability", "Probability", "Basic probability + odds", "math", "Dice5"),
  C("ap-gp-fib", "AP / GP / Fibonacci", "Sequence terms + sum", "math", "ListOrdered"),
  C("percent-error", "Percent Error", "Expected vs actual", "math", "AlertCircle"),
  C("percent-change", "Percent Change", "Old to new", "math", "Percent"),
  C("exponent", "Exponent / Power", "b^e", "math", "Superscript"),
  C("root", "n-th Root", "x^(1/n)", "math", "Subscript"),
  C("scientific-notation", "Scientific Notation", "Number → mantissa × 10ⁿ", "math", "Hash"),
  C("rounding", "Rounding", "Round / floor / ceil", "math", "ArrowDownUp"),
  C("half-life", "Half-Life", "Decay formula", "math", "TrendingDown"),
  C("pythagorean", "Pythagorean", "c = √(a² + b²)", "math", "Triangle"),
  C("right-triangle", "Right Triangle", "Sides + angles + area", "math", "Triangle"),
  C("triangle-general", "Triangle (general)", "Heron's formula", "math", "Triangle"),
  C("slope", "Slope & Intercept", "From two points", "math", "TrendingUp"),
  C("distance-2d", "Distance (2D)", "Between two points", "math", "Move"),
  C("circle", "Circle", "Area, circumference", "math", "Circle"),
  C("shape-area", "Area (shapes)", "Multi-shape area", "math", "Square"),
  C("shape-volume", "Volume (shapes)", "Multi-shape volume", "math", "Box"),
  C("shape-surface", "Surface Area (shapes)", "Multi-shape surface", "math", "Box"),
  C("ratio-simplifier", "Ratio Simplifier", "Reduce a:b:c by GCD", "math", "Divide"),
  C("proportion-solver", "Proportion Solver", "a/b = c/x", "math", "Equal"),
  C("random-number", "Random Number Generator", "Range + count", "math", "Dice5"),
  C("dice-roller", "Dice Roller", "N-sided dice, multi-roll", "math", "Dice5"),

  // ── Geometry — 18 new ──────────────────────────────────────────────────
  C("triangle-solver", "Triangle (full)", "All sides + angles", "geometry", "Triangle"),
  C("right-triangle-geo", "Right Triangle", "Two legs → hyp + area", "geometry", "Triangle"),
  C("equilateral-triangle", "Equilateral Triangle", "Area + height", "geometry", "Triangle"),
  C("pythagorean-geo", "Pythagorean Theorem", "c² = a² + b²", "geometry", "Triangle"),
  C("circle-geo", "Circle", "Area, circ, diameter", "geometry", "Circle"),
  C("ellipse", "Ellipse", "Area + perimeter", "geometry", "Circle"),
  C("square", "Square", "Side → area, diagonal", "geometry", "Square"),
  C("rectangle", "Rectangle", "L×W → area, perimeter, diag", "geometry", "Square"),
  C("parallelogram", "Parallelogram", "Base × height", "geometry", "Square"),
  C("trapezoid", "Trapezoid", "(a+b)·h / 2", "geometry", "Diamond"),
  C("regular-polygon", "Regular Polygon", "n sides + side length", "geometry", "Hexagon"),
  C("cube", "Cube", "Volume + surface", "geometry", "Box"),
  C("cuboid", "Cuboid", "L × W × H", "geometry", "Box"),
  C("sphere", "Sphere", "4/3·π·r³", "geometry", "Globe"),
  C("cylinder", "Cylinder", "π·r²·h", "geometry", "Cylinder"),
  C("cone", "Cone", "π·r²·h/3", "geometry", "Cone"),
  C("pyramid", "Pyramid", "Base² × h / 3", "geometry", "Triangle"),
  C("torus", "Torus", "Donut volume + surface", "geometry", "Circle"),

  // ── Health (8 existing + 24 new = 32) ──────────────────────────────────
  C("bmi", "BMI Calculator", "Body mass index", "health", "HeartPulse", { hasChart: true }),
  C("bmr", "BMR Calculator", "Basal metabolic rate", "health", "Flame"),
  C("calorie", "Calorie Needs", "TDEE & daily calories", "health", "Apple"),
  C("body-fat", "Body Fat %", "US Navy method", "health", "User"),
  C("ideal-weight", "Ideal Weight", "Healthy weight range", "health", "Scale"),
  C("water-intake", "Water Intake", "Daily hydration goal", "health", "Droplet"),
  C("pregnancy", "Pregnancy Due Date", "EDD & trimester", "health", "Baby"),
  C("macro", "Macro Splitter", "P/C/F split", "health", "PieChart", {
    hasChart: true,
    has3DView: true,
  }),
  C("healthy-weight-range", "Healthy Weight Range", "BMI 18.5–25 by height", "health", "Scale"),
  C("lean-body-mass", "Lean Body Mass", "Boer formula", "health", "User"),
  C("army-body-fat", "Army/Navy Body Fat", "US Navy log eqn", "health", "Activity"),
  C("one-rep-max", "One Rep Max (1RM)", "Epley / Brzycki / Lombardi", "health", "Dumbbell"),
  C("target-heart-rate", "Target Heart Rate", "Karvonen zones", "health", "HeartPulse"),
  C("max-heart-rate", "Max Heart Rate", "220 − age", "health", "Heart"),
  C("calories-burned", "Calories Burned", "By activity (MET)", "health", "Flame"),
  C("pace", "Running Pace", "Min/km + speed", "health", "Footprints"),
  C("pace-predictor", "Pace Predictor", "Riegel formula", "health", "TrendingUp"),
  C("vo2-max", "VO₂ Max", "Cooper 12-min test", "health", "Wind"),
  C("body-surface-area", "Body Surface Area", "Du Bois formula", "health", "User"),
  C("body-type", "Somatotype", "Ecto/meso/endo", "health", "User"),
  C("carb-intake", "Carbohydrate Intake", "g/day", "health", "Apple"),
  C("protein-intake", "Protein Intake", "By body weight & activity", "health", "Beef"),
  C("fat-intake", "Fat Intake", "g/day", "health", "Egg"),
  C("tdee", "TDEE", "Total daily expenditure", "health", "Flame"),
  C("calorie-goal", "Calorie Goal", "Cut / maintain / bulk", "health", "Target"),
  C("pregnancy-weight-gain", "Pregnancy Weight Gain", "By pre-BMI", "health", "Baby"),
  C("ovulation", "Ovulation / Fertility", "Fertile window", "health", "Heart"),
  C("period-tracker", "Period Tracker", "Next period date", "health", "Calendar"),
  C("sleep", "Sleep Calculator", "90-min cycle bedtimes", "health", "Moon"),
  C("bac", "Blood Alcohol", "Widmark BAC", "health", "Wine"),
  C("gfr", "GFR (kidney)", "Estimated GFR + CKD stage", "health", "Activity"),
  C("steps-to-calories", "Steps to Calories", "Pedometer kcal", "health", "Footprints"),

  // ── Date & Time (5 existing + 9 new = 14) ──────────────────────────────
  C("age", "Age Calculator", "Years, months, days", "datetime", "Cake"),
  C("date-diff", "Date Difference", "Days between two dates", "datetime", "CalendarDays"),
  C("date-add", "Add / Subtract Days", "Date arithmetic", "datetime", "CalendarPlus"),
  C("working-days", "Working Days", "Business days between dates", "datetime", "Briefcase"),
  C("timezone", "Time Zone Converter", "Multiple zones", "datetime", "Globe"),
  C("time-arith", "Time Calculator", "Add / subtract hh:mm", "datetime", "Clock"),
  C("timesheet", "Time Card / Timesheet", "Weekly hours + OT", "datetime", "Briefcase"),
  C("hours-between", "Hours Between Times", "Duration", "datetime", "Timer"),
  C("day-of-week", "Day of Week", "Mon..Sun for a date", "datetime", "Calendar"),
  C("day-counter", "Day Counter", "Days between dates", "datetime", "CalendarDays"),
  C("countdown", "Countdown", "Days/h/m to target", "datetime", "Timer"),
  C("stopwatch", "Stopwatch", "Elapsed time formatter", "datetime", "Timer"),
  C("pomodoro", "Pomodoro Timer", "Session + breaks total", "datetime", "Clock"),
  C("gestational-age", "Gestational Age", "Weeks pregnant", "datetime", "Baby"),

  // ── Crypto & Stock (6 existing + 14 new = 20) ──────────────────────────
  C("crypto-profit", "Crypto Profit", "Entry → exit profit/loss", "crypto", "Coins", {
    hasChart: true,
  }),
  C("staking-yield", "Staking Yield", "APY rewards projection", "crypto", "TrendingUp", {
    hasChart: true,
  }),
  C("dca", "Dollar-Cost Averaging", "DCA simulation", "crypto", "Repeat", {
    hasChart: true,
    has3DView: true,
  }),
  C("stock-average", "Stock Average", "Average price calc", "crypto", "Activity"),
  C("pe-ratio", "P/E Ratio", "Price-earnings ratio", "crypto", "BarChart"),
  C("position-size", "Position Size", "Risk-based size", "crypto", "Target"),
  C("crypto-tax-india", "Crypto Tax India", "30% + 1% TDS", "crypto", "FileText"),
  C("mining-profit", "Mining Profit", "Hash + power → profit", "crypto", "Cpu"),
  C("impermanent-loss", "Impermanent Loss", "LP vs hold", "crypto", "TrendingDown"),
  C("apy-apr", "APY ↔ APR", "Convert between APY and APR", "crypto", "Repeat"),
  C("liquidation-price", "Liquidation Price", "Margin trade liq", "crypto", "AlertTriangle"),
  C("leverage-margin", "Leverage / Margin", "Effective leverage", "crypto", "Scale"),
  C("risk-reward", "Risk:Reward", "Trade R:R", "crypto", "Scale"),
  C("pip-value", "Pip Value (Forex)", "Per-lot pip $", "crypto", "DollarSign"),
  C("forex-position", "Forex Position Size", "Lots from risk", "crypto", "Target"),
  C(
    "stock-brokerage-india",
    "Stock Brokerage (India)",
    "Full charges + net PnL",
    "crypto",
    "Briefcase",
  ),
  C("stock-profit", "Stock Profit", "Qty × (sell − buy)", "crypto", "TrendingUp"),
  C("stop-loss", "Stop Loss", "From account risk", "crypto", "AlertOctagon"),
  C("take-profit", "Take Profit", "From R:R", "crypto", "Target"),
  C("eps-book-value", "EPS / Book Value", "Per-share fundamentals", "crypto", "BarChart"),

  // ── Converters (10 existing + 20 new = 30) ─────────────────────────────
  C("length", "Length", "m, ft, mi, km, in...", "converter", "Ruler"),
  C("mass", "Mass / Weight", "kg, lb, oz, g...", "converter", "Weight"),
  C("temperature", "Temperature", "°C, °F, K", "converter", "Thermometer"),
  C("area", "Area", "m², ft², acre...", "converter", "Square"),
  C("volume", "Volume", "L, gal, m³...", "converter", "Box"),
  C("speed", "Speed", "km/h, mph, m/s...", "converter", "Gauge"),
  C("time-units", "Time Units", "sec, min, hr, day...", "converter", "Clock"),
  C("data-storage", "Data Storage", "B, KB, MB, GB, TB", "converter", "Database"),
  C("energy", "Energy", "J, kWh, cal...", "converter", "Zap"),
  C("pressure", "Pressure", "Pa, bar, psi, atm", "converter", "Wind"),
  C("angle", "Angle", "deg / rad / grad", "converter", "Compass"),
  C("force", "Force", "N, lbf, kgf", "converter", "Hand"),
  C("torque", "Torque", "Nm, lb·ft", "converter", "RotateCw"),
  C("power", "Power", "W, kW, hp, BTU/hr", "converter", "Zap"),
  C("frequency", "Frequency", "Hz, kHz, RPM", "converter", "Radio"),
  C("fuel-economy", "Fuel Economy", "mpg ↔ km/L", "converter", "Fuel"),
  C("density", "Density", "kg/m³, g/cm³, lb/ft³", "converter", "Box"),
  C("acceleration", "Acceleration", "m/s², ft/s², g", "converter", "Gauge"),
  C("magnetic-flux", "Magnetic Flux", "Weber / Maxwell", "converter", "Magnet"),
  C("current", "Current", "A, mA, µA", "converter", "Zap"),
  C("voltage", "Voltage", "V, mV, kV", "converter", "Zap"),
  C("resistance", "Resistance", "Ω, kΩ, MΩ", "converter", "Zap"),
  C("capacitance", "Capacitance", "F, μF, nF, pF", "converter", "Battery"),
  C("roman-numeral", "Roman Numeral", "Decimal ↔ Roman", "converter", "Hash"),
  C("number-words", "Number to Words", "12345 → words", "converter", "Type"),
  C("indian-number-system", "Indian Number System", "Lakh / crore", "converter", "IndianRupee"),
  C("shoe-size", "Shoe Size", "US/UK/EU/JP", "converter", "Footprints"),
  C("clothing-size", "Clothing Size", "XS–XXL", "converter", "Shirt"),
  C("ring-size", "Ring Size", "mm ↔ US/UK", "converter", "Circle"),
  C("bra-size", "Bra Size", "EU sizing", "converter", "User"),

  // ── Construction — 22 new ──────────────────────────────────────────────
  C("concrete-slab", "Concrete (slab)", "L × W × D + cement bags", "construction", "Square"),
  C("concrete-column", "Concrete (column/footing)", "Round or rect", "construction", "Box"),
  C(
    "cement-sand-aggregate",
    "Cement / Sand / Aggregate",
    "Mix ratio breakdown",
    "construction",
    "Boxes",
  ),
  C("mortar-plaster", "Mortar / Plaster", "Wall area + thickness", "construction", "PaintBucket"),
  C("brick-count", "Brick Count", "Wall l × h × t", "construction", "Bricks"),
  C("block-count", "Block Count", "By block size", "construction", "Bricks"),
  C("tile", "Tile Calculator", "Room + waste %", "construction", "Square"),
  C("flooring", "Flooring", "Planks needed", "construction", "Square"),
  C("carpet", "Carpet", "Length + strips", "construction", "Square"),
  C("paint", "Paint Calculator", "Coats + coverage", "construction", "PaintBucket"),
  C("wallpaper", "Wallpaper", "Rolls needed", "construction", "Square"),
  C("roofing", "Roofing (shingles)", "Roof area", "construction", "Home"),
  C("roof-pitch", "Roof Pitch", "Rise/run → angle", "construction", "Triangle"),
  C("drywall", "Drywall", "Sheets needed", "construction", "Square"),
  C("lumber-board-feet", "Lumber (Board Feet)", "Qty × t × w × l / 12", "construction", "Box"),
  C("stud-wall", "Stud Wall Framing", "Studs per wall", "construction", "Columns3"),
  C("rebar", "Rebar", "Slab grid + total length", "construction", "Cable"),
  C("stair", "Stair Calculator", "Steps + tread depth", "construction", "TrendingUp"),
  C("mulch-topsoil", "Mulch / Topsoil", "Volume m³", "construction", "Sprout"),
  C("gravel", "Gravel", "Volume + weight", "construction", "Mountain"),
  C("fence", "Fence", "Posts + panels", "construction", "Fence"),
  C("pool-volume", "Pool Volume / Fill", "Volume + litres", "construction", "Droplet"),

  // ── Automotive — 12 new ────────────────────────────────────────────────
  C("fuel-cost", "Fuel Cost", "Trip cost from km + price", "automotive", "Fuel"),
  C("mileage", "Mileage (km/L)", "Distance / fuel used", "automotive", "Gauge"),
  C("trip-cost", "Trip Cost (multi-leg)", "Sum of all legs", "automotive", "MapPin"),
  C("horsepower", "Horsepower", "Torque × RPM", "automotive", "Zap"),
  C(
    "engine-displacement",
    "Engine Displacement",
    "Bore, stroke, cyl → cc",
    "automotive",
    "Settings",
  ),
  C("tire-size", "Tire Size", "205/55R16 → diameter", "automotive", "Circle"),
  C("speed-avg", "Average Speed", "Distance / time", "automotive", "Gauge"),
  C("travel-time", "Travel Time", "Distance / speed", "automotive", "Clock"),
  C("lap-time", "Lap Time / Race Pace", "Track + total time", "automotive", "Flag"),
  C("toll-estimate", "Toll Estimator", "₹ by distance + class", "automotive", "Coins"),
  C(
    "ev-charging-cost",
    "EV Charging Cost",
    "Battery × rate / eff",
    "automotive",
    "BatteryCharging",
  ),
  C("ev-vs-petrol", "EV vs Petrol", "Annual cost comparison", "automotive", "GitCompare"),

  // ── Physics — 25 new ───────────────────────────────────────────────────
  C("force", "Force (F = ma)", "Newton's 2nd law", "physics", "Atom"),
  C("newton-second", "Newton's 2nd (solver)", "Solve for any of F, m, a", "physics", "Atom"),
  C("weight", "Weight (mg)", "On Earth / Moon / Mars", "physics", "Scale"),
  C("kinetic-energy", "Kinetic Energy", "½·m·v²", "physics", "Activity"),
  C("potential-energy", "Potential Energy", "m·g·h", "physics", "ArrowUp"),
  C("work", "Work (F·d·cos θ)", "Work done", "physics", "Hammer"),
  C("physics-power", "Power (W/t)", "Power", "physics", "Zap"),
  C("momentum", "Momentum", "p = m·v", "physics", "Move"),
  C("impulse", "Impulse", "J = F·t", "physics", "Zap"),
  C("velocity-uat", "Velocity (v = u + at)", "Kinematics", "physics", "TrendingUp"),
  C("acceleration", "Acceleration", "Δv / t", "physics", "Gauge"),
  C("free-fall", "Free Fall", "Time + impact velocity", "physics", "ArrowDown"),
  C("projectile-motion", "Projectile Motion", "Range, height, flight", "physics", "MoveRight"),
  C("friction", "Friction Coefficient", "μ = F/N", "physics", "Activity"),
  C("pressure", "Pressure", "F / A", "physics", "Gauge"),
  C("physics-density", "Density", "m / V", "physics", "Box"),
  C("buoyancy", "Buoyancy", "ρ·V·g", "physics", "Anchor"),
  C("ohms-law", "Ohm's Law", "V, I, R + P", "physics", "Zap"),
  C("electrical-power", "Electrical Power", "P = V·I", "physics", "Zap"),
  C("resistor-network", "Resistor Network", "Series / parallel", "physics", "GitMerge"),
  C("capacitor-network", "Capacitor Network", "Series / parallel", "physics", "Battery"),
  C("wave-equation", "Wave Equation", "λ = v/f", "physics", "Radio"),
  C("doppler", "Doppler Effect", "Frequency shift", "physics", "Radio"),
  C("pendulum", "Pendulum Period", "2π·√(L/g)", "physics", "Activity"),
  C("hooke-spring", "Hooke's Law (spring)", "F = k·x", "physics", "Activity"),

  // ── Chemistry — 15 new ─────────────────────────────────────────────────
  C("molarity", "Molarity", "mol/L", "chemistry", "FlaskRound"),
  C("molality", "Molality", "mol/kg", "chemistry", "FlaskConical"),
  C("molar-mass", "Molar Mass", "From formula", "chemistry", "Atom"),
  C("moles-mass-atoms", "Moles ↔ Mass ↔ Atoms", "Convert between three", "chemistry", "Atom"),
  C("mass-percent", "Mass Percent", "% w/w", "chemistry", "Percent"),
  C("dilution", "Dilution (M₁V₁=M₂V₂)", "Solve for final volume", "chemistry", "FlaskRound"),
  C("ph", "pH / pOH", "From [H⁺]", "chemistry", "TestTube"),
  C("buffer", "Buffer (Henderson-H)", "Buffer pH", "chemistry", "FlaskConical"),
  C("ideal-gas", "Ideal Gas (PV=nRT)", "Moles from P, V, T", "chemistry", "Wind"),
  C("boyle-charles", "Boyle / Charles", "Gas law variants", "chemistry", "Wind"),
  C("half-life-radio", "Half-Life (radioactive)", "Decay over time", "chemistry", "TrendingDown"),
  C("empirical-formula", "Empirical Formula", "From mass %", "chemistry", "Beaker"),
  C("avogadro", "Avogadro / Mole", "Atoms ↔ moles", "chemistry", "Atom"),
  C("chem-density", "Density (chem)", "m / V", "chemistry", "Box"),
  C(
    "solution-concentration",
    "Solution Concentration",
    "mg/L ↔ ppm ↔ %",
    "chemistry",
    "FlaskRound",
  ),

  // ── Electrical — 12 new ────────────────────────────────────────────────
  C("ohms-full", "Ohm's Law (full)", "Solve for V, I, R or P", "electrical", "Zap"),
  C("resistor-color-code", "Resistor Color Code", "4-band → resistance", "electrical", "Palette"),
  C("resistor-color-reverse", "Resistor (reverse)", "Resistance → colors", "electrical", "Palette"),
  C("voltage-drop", "Voltage Drop", "Wire length + gauge", "electrical", "TrendingDown"),
  C("wire-gauge", "Wire Gauge (AWG)", "By current + length", "electrical", "Cable"),
  C("led-resistor", "LED Series Resistor", "Vs − Vled / I", "electrical", "Lightbulb"),
  C("rc-time", "RC Time Constant", "τ = R·C", "electrical", "Activity"),
  C("rl-time", "RL Time Constant", "τ = L/R", "electrical", "Activity"),
  C("decibel", "Decibel (dB)", "Power or voltage ratio", "electrical", "Volume2"),
  C("power-factor", "Power Factor", "Real / apparent", "electrical", "Zap"),
  C("battery-life", "Battery Life", "mAh ÷ mA", "electrical", "Battery"),
  C("solar-panel-sizing", "Solar Panel Sizing", "Daily load × sun-hours", "electrical", "Sun"),

  // ── Cooking — 10 new ───────────────────────────────────────────────────
  C("recipe-scaler", "Recipe Scaler", "Servings new/old", "cooking", "ChefHat"),
  C("cups-to-grams", "Cups ↔ Grams", "By ingredient", "cooking", "CupSoda"),
  C("tbsp-tsp-ml", "Tbsp ↔ tsp ↔ ml", "Volume conversions", "cooking", "Beaker"),
  C("oven-temp", "Oven Temp", "°C ↔ °F ↔ Gas Mark", "cooking", "Flame"),
  C("pan-conversion", "Baking Pan Conversion", "Area ratio", "cooking", "Square"),
  C("cooking-time", "Cooking Time", "By meat + weight", "cooking", "Timer"),
  C("yeast-sugar", "Bread (yeast / sugar / water)", "From flour weight", "cooking", "Wheat"),
  C("coffee-ratio", "Coffee Ratio", "1:N brew ratio", "cooking", "Coffee"),
  C("abv", "Alcohol ABV", "OG / FG → ABV", "cooking", "Wine"),
  C("macros-per-recipe", "Macros per Recipe", "Per-serving macros", "cooking", "PieChart"),

  // ── Lifestyle — 15 new ─────────────────────────────────────────────────
  C("gpa", "GPA", "4.0 / 10.0 scale", "lifestyle", "GraduationCap"),
  C("cgpa-percentage", "CGPA ↔ %", "Convert CGPA to percentage", "lifestyle", "Percent"),
  C("exam-grade-needed", "Exam Grade Needed", "To hit target final %", "lifestyle", "Target"),
  C(
    "exam-score-predictor",
    "Exam Score Predictor",
    "With negative marking",
    "lifestyle",
    "FileCheck",
  ),
  C("tip-calculator-lifestyle", "Tip Calculator", "Tip + total", "lifestyle", "HandCoins"),
  C("split-bill", "Split Bill", "Per-person with tip", "lifestyle", "Users"),
  C("love-compatibility", "Love Compatibility (fun)", "Name-based", "lifestyle", "Heart"),
  C("name-numerology", "Name Numerology", "Destiny number", "lifestyle", "Hash"),
  C("age-in-units", "Age in Days/Hours", "Exact units", "lifestyle", "Clock"),
  C("zodiac-western", "Zodiac Sign", "From DOB", "lifestyle", "Stars"),
  C("chinese-zodiac", "Chinese Zodiac", "From birth year", "lifestyle", "Stars"),
  C("anniversary", "Wedding Anniversary", "Years + symbol", "lifestyle", "Heart"),
  C("retirement-countdown", "Retirement Countdown", "Years until retire", "lifestyle", "Timer"),
  C("carbon-footprint", "Carbon Footprint", "Tonnes CO₂/yr", "lifestyle", "Leaf"),
  C("water-footprint", "Water Footprint", "L/day", "lifestyle", "Droplet"),

  // ── Developer — 14 new ─────────────────────────────────────────────────
  C("ip-subnet", "IP Subnet (CIDR)", "Mask, hosts, broadcast", "developer", "Globe"),
  C("subnet-mask-converter", "Subnet Mask Converter", "Dotted ↔ CIDR", "developer", "Globe"),
  C("mac-lookup", "MAC Address Lookup", "OUI vendor (offline)", "developer", "Wifi"),
  C("base64", "Base64 Encode/Decode", "Text ↔ Base64", "developer", "Code"),
  C("url-encode", "URL Encode/Decode", "Percent encoding", "developer", "Link"),
  C("html-entity", "HTML Entity", "< > & encoding", "developer", "Code"),
  C("hash-generator", "Hash Generator", "SHA-1/256/384/512", "developer", "Lock"),
  C("uuid-generator", "UUID Generator", "v4 UUIDs", "developer", "Fingerprint"),
  C("password-generator", "Password Generator", "Length + charset", "developer", "Key"),
  C("password-strength", "Password Strength", "Entropy verdict", "developer", "Shield"),
  C("random-string", "Random String", "Charset + length", "developer", "Shuffle"),
  C("bandwidth", "Bandwidth / Download Time", "File size ÷ speed", "developer", "Download"),
  C("color-converter", "Color Converter", "HEX ↔ RGB ↔ HSL", "developer", "Palette"),
  C("cron-helper", "Cron Expression Helper", "Minutes/hours fields", "developer", "Clock"),

  // ── Weather — 7 new ────────────────────────────────────────────────────
  C("wind-chill", "Wind Chill", "Apparent temp from wind", "weather", "Wind"),
  C("heat-index", "Heat Index", "Feels-like w/ humidity", "weather", "Thermometer"),
  C("dew-point", "Dew Point", "Temp + humidity", "weather", "Droplet"),
  C("humidity", "Humidity (RH ↔ abs)", "Relative ↔ absolute", "weather", "Droplets"),
  C("uv-exposure", "UV Exposure", "Time to burn", "weather", "Sun"),
  C("sunrise-sunset", "Sunrise / Sunset", "Lat/lon → times", "weather", "Sunrise"),
  C("moon-phase", "Moon Phase", "Phase + illumination", "weather", "Moon"),

  // ── Sports — 8 new ─────────────────────────────────────────────────────
  C("cricket-run-rate", "Cricket Run Rate", "RPO", "sports", "Trophy"),
  C("cricket-required-rr", "Cricket Required RR", "Chase math", "sports", "Trophy"),
  C("cricket-dls", "Cricket DLS (simplified)", "Revised target", "sports", "CloudRain"),
  C("cricket-stats", "Cricket Stats", "Strike rate, avg, economy", "sports", "BarChart3"),
  C("golf-handicap", "Golf Handicap", "From recent scores", "sports", "Flag"),
  C("bowling-score", "Bowling (10-pin) Score", "Frame total", "sports", "Target"),
  C("darts-checkout", "Darts Checkout", "From remaining score", "sports", "Target"),
  C("fantasy-cricket", "Fantasy Cricket Points", "Runs + wickets + catches", "sports", "Trophy"),
];

const categoryIndex = new Map<Category, CalculatorMeta[]>();
const slugIndex = new Map<string, CalculatorMeta>();
for (const c of CALCULATORS) {
  slugIndex.set(c.id, c);
  const list = categoryIndex.get(c.category) ?? [];
  list.push(c);
  categoryIndex.set(c.category, list);
}

export function getCalculatorsByCategory(category: Category): CalculatorMeta[] {
  return categoryIndex.get(category) ?? [];
}

export function getCalculatorBySlug(slug: string): CalculatorMeta | undefined {
  return slugIndex.get(slug);
}

export function getAllCalculators(): CalculatorMeta[] {
  return CALCULATORS;
}

export function getCategoryBySlug(slug: string): CategoryMeta | undefined {
  return CATEGORIES.find((c) => c.id === slug);
}
