import type { Category } from "@/types/calculator";

export const CATEGORY_BADGE_CLASS: Record<Category, string> = {
  finance: "bg-finance/15 text-finance",
  "finance-india": "bg-finance/20 text-finance",
  math: "bg-math/15 text-math",
  health: "bg-health/15 text-health",
  converter: "bg-converter/15 text-converter",
  datetime: "bg-datetime/15 text-datetime",
  crypto: "bg-crypto/15 text-crypto",
  geometry: "bg-primary/15 text-primary",
  construction: "bg-accent/15 text-accent",
  automotive: "bg-secondary/15 text-secondary",
  physics: "bg-datetime/15 text-datetime",
  chemistry: "bg-health/15 text-health",
  electrical: "bg-accent/15 text-accent",
  cooking: "bg-error/15 text-error",
  lifestyle: "bg-secondary/15 text-secondary",
  developer: "bg-text-secondary/15 text-text",
  weather: "bg-datetime/15 text-datetime",
  sports: "bg-success/15 text-success",
};

export const CATEGORY_BG_SOFT_CLASS: Record<Category, string> = {
  finance: "bg-finance/10",
  "finance-india": "bg-finance/10",
  math: "bg-math/10",
  health: "bg-health/10",
  converter: "bg-converter/10",
  datetime: "bg-datetime/10",
  crypto: "bg-crypto/10",
  geometry: "bg-primary/10",
  construction: "bg-accent/10",
  automotive: "bg-secondary/10",
  physics: "bg-datetime/10",
  chemistry: "bg-health/10",
  electrical: "bg-accent/10",
  cooking: "bg-error/10",
  lifestyle: "bg-secondary/10",
  developer: "bg-surface",
  weather: "bg-datetime/10",
  sports: "bg-success/10",
};

export const CATEGORY_TEXT_CLASS: Record<Category, string> = {
  finance: "text-finance",
  "finance-india": "text-finance",
  math: "text-math",
  health: "text-health",
  converter: "text-converter",
  datetime: "text-datetime",
  crypto: "text-crypto",
  geometry: "text-primary",
  construction: "text-accent",
  automotive: "text-secondary",
  physics: "text-datetime",
  chemistry: "text-health",
  electrical: "text-accent",
  cooking: "text-error",
  lifestyle: "text-secondary",
  developer: "text-text",
  weather: "text-datetime",
  sports: "text-success",
};

export const CATEGORY_RING_CLASS: Record<Category, string> = {
  finance: "ring-finance/30",
  "finance-india": "ring-finance/30",
  math: "ring-math/30",
  health: "ring-health/30",
  converter: "ring-converter/30",
  datetime: "ring-datetime/30",
  crypto: "ring-crypto/30",
  geometry: "ring-primary/30",
  construction: "ring-accent/30",
  automotive: "ring-secondary/30",
  physics: "ring-datetime/30",
  chemistry: "ring-health/30",
  electrical: "ring-accent/30",
  cooking: "ring-error/30",
  lifestyle: "ring-secondary/30",
  developer: "ring-border",
  weather: "ring-datetime/30",
  sports: "ring-success/30",
};
